spring.application.name=politis-client-spring
spring.main.web-application-type=NONE

#DB Configuration
spring.datasource.url=jdbc:mysql://${DB_HOST}/${DB_NAME}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

service.host=localhost
service.port=8080
service.api=api/politis
