


on:
    push:
        branches:
            - develop
            
            
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code
            uses: actions/checkout@v4
            
          - name: Set up JDK 21
            uses: actions/setup-java@v4
            with:
                java-version: '21'
                distribution: 'adopt'            
            
          - name: Compile, Unit Test and Install
            id: unit-tests
            run: mvn clean install
            
          - name: Upload test reports
            if: always() 
            uses: actions/upload-artifact@v4
            with:
                name: test-reports
                path: '**/target/surefire-reports/*.xml'
                
                
          - name: integration Test 
            id: integration-tests
            run: nvm failsafe:integration-test
            
          - name: Upload integration test reports
            if: always() 
            uses: actions/upload-artifact@v4
            with:
                name: integration-test-reports
                path: '**/target/failsafe-reports/*.xml'
